version: '3'

services:
  node:
    build: 
      context: ./appnode
      dockerfile: Dockerfile
    container_name: node
    entrypoint: sh -c "npm install && node index.js"
    networks:
      - netRudi
    volumes:
      - ./appnode:/usr/src/app
    ports:
      - "3000:3000"      

  nginx:
    build: 
      context: ./appnginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - netRudi
    ports:
      - "8080:80"
    depends_on:
      - node

networks:
  netRudi:
    name: netRudi
    driver: bridge