version: '3'

services:
  node:
    build: 
      context: ./appnode
      dockerfile: Dockerfile
    image: claudemirribeiro/appnode
    container_name: node
    networks:
      - netRudi
    ports:
      - "3000:3000"      

  nginx:
    build: 
      context: ./appnginx
      dockerfile: Dockerfile
    image: claudemirribeiro/appnginx
    container_name: nginx
    volumes:
      - ./appnginx/default.com:/etc/nginx/conf.d/default.conf
    networks:
      - netRudi
    ports:
      - "80:80"
    depends_on:
      - node

networks:
  netRudi:
    name: netRudi
    driver: bridge